### ISSUE TITLE
Build out test suite

### ISSUE THREAD

**Issue by gambogi** [ComputerScienceHouse/csh-eval#28]
We have listed test coverage as a project goal. Let's put in the work to make that happen.

**Comment by TravisWhitaker** [comment]
It might be too ambitious, but it would be nice to write HUnit tests that confirm the invariants of the schema. The tests would have to look for a local PostgreSQL server, set up the schema in a test database, simulate some API calls, and clean up after itself.

**Comment by gambogi** [comment]
My idea when writing this issue was the fact that our current test suite is `main = undefined`. 
If our unit tests make assumptions about the environment they run in we should document those assumptions, and keep them separate from tests that have no environmental dependencies.

**Comment by TravisWhitaker** [comment]
Right, we should separate pure tests (i.e. QuickCheck) from effectful tests (i.e. HUnit). Are we allowed to make more than one "test" target in the cabal file?

**Comment by TravisWhitaker** [comment]
It would be good to include HPC checks for test coverage as well.

**Comment by gambogi** [comment]
Update: using tasty to orchestrate unit tests/ property tests.
