### ISSUE TITLE
Convert to hasql

### ISSUE THREAD

**Issue by gambogi** [ComputerScienceHouse/csh-eval#40]
[hasql](https://hackage.haskell.org/package/hasql) (ha! sql!) is a efficient, pure haskell library for interacting with databases. 
We favor it over HDBC because of it's speed and type safety. We can now eliminate all raw SQL from the application.

**Comment by harlanhaskins** [comment]
Well, to be fair, Hasql uses raw sql queries. It's not an ORM, it just adds a type-safe layer on top of raw sql.

**Comment by gambogi** [comment]
This will absorb `db/eval_schema.sql`, in addition to replacing HDBC
