### ISSUE TITLE
Establish Nightly Builds

### ISSUE THREAD

**Issue by gambogi** [ComputerScienceHouse/csh-eval#63]
We need to ensure that a fresh build will always work. Recently we ran into an issue where one of our dependencies updated an the entire build broke. This is not a good sign, and should really be addressed.

There are two options: Run nightlies to detect these problems, or use stackage to guarantee these problems won't arise.

One or both are acceptable.
This should be a good resource to get started: https://circleci.com/docs/nightly-builds

**Comment by cgonyeo** [comment]
circleci build should now run every day at 12:30 am. I'll close this tomorrow once I can confirm it runs correctly tonight.

**Comment by cgonyeo** [comment]
Yup, nightlies are now working.
