### ISSUE TITLE
Create widget structure

### ISSUE THREAD

**Issue by gambogi** [ComputerScienceHouse/csh-eval#68]
We need examples and a place to put widgets. A good first widget would be the `widgetPanel`

**Comment by sdemos** [comment]
For posterity: 
We want to have reusable widgets that people can use while building pages, such as a basic panel or a panel with a member's information. These reusable widgets will be functions that take some arguments and transform them into a widget that can be embedded into a page using the whamlet `^{widgetName arg1 arg2}` syntax described in the [Yesod Book chapter on Widgets](http://www.yesodweb.com/book/widgets).
