### ISSUE TITLE
Investigate CircleCI build failures

### ISSUE THREAD

**Issue by sdemos** [ComputerScienceHouse/csh-eval#97]
I'm not sure what is causing the build failures on circle. It seems to be failing on something we couldn't have caused. Someone should play around with it. 

If this is an issue with circle, we should report the issue and see if they can resolve it.

**Comment by sdemos** [comment]
Some part of this issue came from us not using `cabal update` before installing stack. Also, stack wasn't installing it's own ghc to the instance, so it was behind on the ghc version, which seemed to cause some errors somehow. Now this issue seems to be isolated to our recent changes. Will investigate further.

**Comment by TravisWhitaker** [comment]
We should probably get CircleCI to use a hosted stack binary; there's no reason to re-build stack itself for each test round.

**Comment by robgssp** [comment]
Stack works now. Fix your tests.
